# Generated by Django 5.2.4 on 2026-09-26 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0002_story_share_count_storyshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_story', 'New story'), ('trending', 'Trending'), ('streak', 'Streak'), ('badge', 'Badge earned'), ('announcement', 'Announcement'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('story_title', models.CharField(blank=True, default='', max_length=200)),
                ('story_slug', models.CharField(blank=True, default='', max_length=250)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=120)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='notif_inbox_idx'), models.Index(fields=['user', 'is_read'], name='notif_unread_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='unique_notification_per_user_dedupe_key')],
            },
        ),
    ]
