# Generated by Django 5.2.17 on 2026-10-07 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Must match a key in settings.PREMIUM_FEATURES.', max_length=64, unique=True)),
                ('label', models.CharField(help_text='Name shown to readers.', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='What the feature includes, for the paywall and admin.')),
                ('enabled', models.BooleanField(default=True, help_text='Live flag. Disabling a premium feature takes it out of service for everyone — entitled readers included — until re-enabled.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order on the paywall. Lower first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement_id', models.CharField(default='premium', help_text='The purchased entitlement; the premium tier is `premium`.', max_length=64)),
                ('provider', models.CharField(choices=[('revenuecat', 'RevenueCat'), ('manual', 'Manual grant')], default='manual', max_length=24)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_subscription_id', models.CharField(blank=True, default='', help_text='Store subscription/product identifier from the webhook.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial / intro offer'), ('cancelled', 'Cancelled (until period end)'), ('expired', 'Expired')], default='active', max_length=16)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Null on grants/intro offers without an expiry.', null=True)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
