# Generated by Django 5.2.17 on 2026-10-08 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier (e.g. `premium_monthly`).', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Shown on the paywall.', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per interval in `currency`.', max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('interval', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=8)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Entitlement length granted per paid period.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans stay on old receipts but cannot be bought.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'key'),
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('revenuecat', 'RevenueCat'), ('manual', 'Manual grant'), ('dev', 'Development checkout')], default='manual', max_length=24),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial / intro offer'), ('pending', 'Pending (awaiting provider confirmation)'), ('cancelled', 'Cancelled (until period end)'), ('expired', 'Expired')], default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('revenuecat', 'RevenueCat'), ('manual', 'Manual (admin-recorded)'), ('dev', 'Development checkout')], default='manual', max_length=24)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', help_text='Store transaction id; empty for manual/dev records.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True, default='', help_text='Human context (e.g. "Development checkout — no charge").')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The plan behind this period; null after a plan is retired.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
    ]
