// Bundled achievement badge seed content for the offline gamification layer.

/// Badges seeded into `local_badges` on every fresh install.
final List<Map<String, Object>> kSeedBadges = [
  {
    'name': 'First Steps',
    'slug': 'first-steps',
    'description': 'Read your first story.',
    'emoji': '👣',
    'category': 'reading',
    'xp_required': 0,
    'color': '#8B4513',
  },
  {
    'name': 'Bookworm',
    'slug': 'bookworm',
    'description': 'Read 5 stories.',
    'emoji': '🐛',
    'category': 'reading',
    'xp_required': 50,
    'color': '#4A6741',
  },
  {
    'name': 'Story Explorer',
    'slug': 'story-explorer',
    'description': 'Read 10 stories.',
    'emoji': '🧭',
    'category': 'reading',
    'xp_required': 100,
    'color': '#C68B29',
  },
  {
    'name': 'Heritage Guardian',
    'slug': 'heritage-guardian',
    'description': 'Read 25 stories.',
    'emoji': '🛡️',
    'category': 'reading',
    'xp_required': 250,
    'color': '#6B4C8A',
  },
  {
    'name': 'Quiz Apprentice',
    'slug': 'quiz-apprentice',
    'description': 'Pass your first quiz.',
    'emoji': '📝',
    'category': 'quiz',
    'xp_required': 30,
    'color': '#B85C38',
  },
  {
    'name': 'Quiz Master',
    'slug': 'quiz-master',
    'description': 'Pass 5 quizzes.',
    'emoji': '🎓',
    'category': 'quiz',
    'xp_required': 150,
    'color': '#C85A32',
  },
  {
    'name': 'Perfect Score',
    'slug': 'perfect-score',
    'description': 'Score 100% on any quiz.',
    'emoji': '💯',
    'category': 'quiz',
    'xp_required': 50,
    'color': '#C68B29',
  },
  {
    'name': 'Streak Warrior',
    'slug': 'streak-warrior',
    'description': 'Maintain a 7-day reading streak.',
    'emoji': '🔥',
    'category': 'streak',
    'xp_required': 100,
    'color': '#B85C38',
  },
  {
    'name': 'Culture Keeper',
    'slug': 'culture-keeper',
    'description': 'Read stories from 3 different regions.',
    'emoji': '🌍',
    'category': 'exploration',
    'xp_required': 75,
    'color': '#4A6741',
  },
  {
    'name': 'Folktales Fan',
    'slug': 'folktales-fan',
    'description': 'Read 5 folktales.',
    'emoji': '📖',
    'category': 'category',
    'xp_required': 50,
    'color': '#8B4513',
  },
  {
    'name': 'Legend Lover',
    'slug': 'legend-lover',
    'description': 'Read 5 legends.',
    'emoji': '⚔️',
    'category': 'category',
    'xp_required': 50,
    'color': '#C68B29',
  },
  {
    'name': 'Bilingual Reader',
    'slug': 'bilingual-reader',
    'description': 'Read stories in both English and French.',
    'emoji': '🌐',
    'category': 'exploration',
    'xp_required': 60,
    'color': '#6B4C8A',
  },
];
