# Generated by Django 5.2.4 on 2026-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the artifact.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from title).', max_length=250, unique=True)),
                ('story', models.TextField(help_text="Narrative description of the artifact's cultural significance.")),
                ('audio_file', models.FileField(blank=True, help_text='Optional audio narration file.', null=True, upload_to='audio/')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube/Vimeo video URL.', null=True)),
                ('qr_code', models.ImageField(blank=True, editable=False, help_text='Auto-generated QR code linking to this artifact.', null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
