# Generated by Django 5.2.4 on 2026-09-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='category',
            field=models.CharField(choices=[('kingdom', 'Kingdom'), ('landmark', 'Landmark'), ('artifact', 'Artifact'), ('legend', 'Legend'), ('culture', 'Culture')], default='culture', help_text='Classification: Kingdom, Landmark, Artifact, Legend, or Culture.', max_length=20),
        ),
        migrations.AddField(
            model_name='artifact',
            name='historical_significance',
            field=models.TextField(blank=True, default='', help_text='Cultural background or legend details.'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City or region (e.g., Foumban, West Region).', max_length=200),
        ),
        migrations.AddField(
            model_name='artifact',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Original source URL of the content.'),
        ),
    ]
