# Generated by Django 5.2.4 on 2026-08-07 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioNarrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, default='default', help_text='Voice ID for TTS provider.', max_length=100)),
                ('language', models.CharField(default='en', help_text='Language code for narration.', max_length=10)),
                ('speed', models.FloatField(default=1.0, help_text='Playback speed multiplier.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('audio_url', models.URLField(blank=True, default='', help_text='URL to the generated audio.')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Audio duration in seconds.')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Audio file size in bytes.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if narration failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_narrations', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='media_app_a_user_id_4e35df_idx'), models.Index(fields=['story', '-created_at'], name='media_app_a_story_i_5224e7_idx'), models.Index(fields=['status'], name='media_app_a_status_2f5352_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luma_job_id', models.CharField(blank=True, default='', help_text='Job ID from Luma AI Dream Machine API.', max_length=255)),
                ('prompt', models.TextField(help_text='Prompt used for video generation.')),
                ('luma_request_id', models.CharField(blank=True, default='', help_text='Request ID for tracking.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0, help_text='Generation progress (0-100).')),
                ('video_url', models.URLField(blank=True, default='', help_text='URL to the generated video.')),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='URL to the video thumbnail.')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Video duration in seconds.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if generation failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_generations', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='media_app_v_user_id_15bfe4_idx'), models.Index(fields=['story', '-created_at'], name='media_app_v_story_i_587db6_idx'), models.Index(fields=['status'], name='media_app_v_status_ffeb5f_idx'), models.Index(fields=['luma_job_id'], name='media_app_v_luma_jo_393fa0_idx')],
            },
        ),
    ]
