# Generated by Django 5.2.4 on 2026-08-08 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('qr_codes', '0001_initial'),
        ('stories', '0002_story_share_count_storyshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='audionarrationjob',
            name='artifact',
            field=models.ForeignKey(blank=True, help_text='Artifact whose story is narrated (audio guide).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_narrations', to='qr_codes.artifact'),
        ),
        migrations.AddField(
            model_name='audionarrationjob',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Generated audio file (MP3).', upload_to='audio/narrations/'),
        ),
        migrations.AddField(
            model_name='audionarrationjob',
            name='narration_text',
            field=models.TextField(blank=True, default='', help_text='Snapshot of the text that was converted to speech.'),
        ),
        migrations.AlterField(
            model_name='audionarrationjob',
            name='audio_url',
            field=models.URLField(blank=True, default='', help_text='Legacy URL to the generated audio (kept for compatibility).'),
        ),
        migrations.AlterField(
            model_name='audionarrationjob',
            name='story',
            field=models.ForeignKey(blank=True, help_text='Story being narrated (story-based narrations).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_narrations', to='stories.story'),
        ),
    ]
