# Generated by Django 5.2.17 on 2026-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_audionarrationjob_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audionarrationjob',
            name='engine',
            field=models.CharField(blank=True, default='', help_text='Name/version of the TTS engine (e.g. gtts).', max_length=40),
        ),
        migrations.AddField(
            model_name='audionarrationjob',
            name='origin_kind',
            field=models.CharField(choices=[('synthetic', 'AI-generated from the story text'), ('human_recording', 'Recorded by a human narrator')], default='synthetic', help_text='Whether the audio was AI-generated or human-recorded.', max_length=30),
        ),
        migrations.AddField(
            model_name='audionarrationjob',
            name='reviewed_by_source',
            field=models.BooleanField(default=False, help_text='A source community member reviewed and approved this narration.'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='engine',
            field=models.CharField(blank=True, default='', help_text='Name/version of the generating model (e.g. luma-dream-machine).', max_length=40),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='origin_kind',
            field=models.CharField(choices=[('synthetic', 'AI-generated from the story text'), ('human_recording', 'Recorded by a human narrator')], default='synthetic', help_text='Whether the video was AI-generated or human-recorded.', max_length=30),
        ),
    ]
