# Generated by Django 5.2.17 on 2026-10-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_audionarrationjob_target_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='video_file',
            field=models.FileField(blank=True, help_text='Stored copy of the generated video (downloaded on completion).', upload_to='video/generations/'),
        ),
    ]
