# Generated by Django 5.2.17 on 2026-10-06 15:36

from django.db import migrations, models


def backfill_provider(apps, schema_editor):
    """Label existing rows with the vendor that actually issued them.

    Before the provider chain there was only Luma, plus the mock. Anything
    with an external job id but no engine credit was a live Luma render;
    anything credited to the mock was not a real render at all and must route
    to the mock on poll, not to a live vendor that would 404 on its id.
    Rows with no job id have nothing to route and stay blank.
    """
    VideoGenerationJob = apps.get_model('media_app', 'VideoGenerationJob')

    VideoGenerationJob.objects.filter(engine='luma-mock').update(provider='mock')
    VideoGenerationJob.objects.filter(
        provider='', luma_job_id__gt=''
    ).exclude(engine='luma-mock').update(provider='luma')


def clear_provider(apps, schema_editor):
    """Reverse is a no-op: the old schema has nowhere to put the value."""


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_videogenerationjob_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Video provider that issued this job (luma, fal, mock).', max_length=20),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='engine',
            field=models.CharField(blank=True, default='', help_text='Name/version of the generating model (e.g. luma-ray-3.2).', max_length=40),
        ),
        migrations.RunPython(backfill_provider, clear_provider),
    ]
