# Generated by Django 5.2.4 on 2026-08-07 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='📖', max_length=10)),
                ('color', models.CharField(blank=True, default='#8B4513', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Story categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField(help_text='Story content in Markdown format.')),
                ('summary', models.TextField(blank=True, default='', help_text='Brief summary for previews (max 500 chars).', max_length=500)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ful', 'Fula'), ('dua', 'Duala'), ('ewo', 'Ewondo'), ('bml', 'Bamileke'), ('other', 'Other')], default='en', max_length=10)),
                ('region', models.CharField(blank=True, default='', help_text='Geographic origin of the story (e.g., Northwest Region).', max_length=100)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags for search and filtering.', max_length=500)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the story.', null=True, upload_to='stories/covers/')),
                ('cover_image_blurhash', models.CharField(blank=True, default='', help_text='BlurHash placeholder for progressive image loading.', max_length=100)),
                ('audio_url', models.URLField(blank=True, default='', help_text='URL to audio narration (Phase 4: TTS/voice).')),
                ('video_url', models.URLField(blank=True, default='', help_text='URL to AI-generated video (Phase 4: Luma AI).')),
                ('cultural_context', models.TextField(blank=True, default='', help_text='Historical and cultural context for the story.')),
                ('moral_lesson', models.TextField(blank=True, default='', help_text='Key moral or teaching from the story.')),
                ('source', models.CharField(blank=True, default='', help_text='Original source or teller of the story.', max_length=200)),
                ('estimated_read_time', models.PositiveIntegerField(default=0, help_text='Estimated read time in minutes.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, default='', help_text='Internal notes from the reviewer.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_stories', to=settings.AUTH_USER_MODEL)),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authored_stories', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='stories', to='stories.storycategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('cultural_inaccuracy', 'Cultural Inaccuracy'), ('inappropriate_content', 'Inappropriate Content'), ('copyright_violation', 'Copyright Violation'), ('wrong_category', 'Wrong Category'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, default='', help_text='Additional details about the flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveIntegerField(default=0, help_text='Reading progress as percentage (0-100).')),
                ('last_read_position', models.PositiveIntegerField(default=0, help_text='Last scroll position or character index.')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='stories.story')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.CreateModel(
            name='StoryBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='', help_text='Personal note about why this story was saved.')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-created_at'], name='stories_sto_created_afacec_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', '-published_at'], name='stories_sto_status_386c74_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author'], name='stories_sto_author__45d8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['language'], name='stories_sto_languag_d5bb7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyflag',
            unique_together={('user', 'story')},
        ),
        migrations.AlterUniqueTogether(
            name='storylike',
            unique_together={('user', 'story')},
        ),
    ]
