# Generated by Django 5.2.17 on 2026-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_share_count_storyshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='consent_status',
            field=models.CharField(choices=[('not_requested', 'Consent not yet requested'), ('pending', 'Consent pending'), ('granted', 'Consent granted'), ('granted_restricted', 'Consent granted with restrictions'), ('withheld', 'Consent withheld')], default='not_requested', help_text='Whether the source community agreed to this publication.', max_length=30),
        ),
        migrations.AddField(
            model_name='story',
            name='licence',
            field=models.CharField(choices=[('all_rights_reserved', 'All rights reserved'), ('cc_by', 'CC BY 4.0'), ('cc_by_sa', 'CC BY-SA 4.0'), ('cc_by_nc', 'CC BY-NC 4.0'), ('cc_by_nc_sa', 'CC BY-NC-SA 4.0'), ('public_domain', 'Public domain'), ('undetermined', 'Undetermined')], default='undetermined', help_text='Licence the text is shared under.', max_length=30),
        ),
        migrations.AddField(
            model_name='story',
            name='origin',
            field=models.CharField(choices=[('community_recorded', 'Recorded from a community member'), ('oral_transcription', 'Transcribed from an oral telling'), ('published_collection', 'From a published collection'), ('contributor_original', 'Original contribution'), ('seeded', 'Seeded demonstration content'), ('unknown', 'Unknown')], default='unknown', help_text='Where this text came from, independently of `source`.', max_length=30),
        ),
        migrations.AddField(
            model_name='story',
            name='provenance_notes',
            field=models.TextField(blank=True, default='', help_text='How this version was obtained (interview, archive, memory).'),
        ),
        migrations.AddField(
            model_name='story',
            name='recorded_at',
            field=models.DateField(blank=True, help_text='When the story was recorded from its source, if it was.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='rights_holder',
            field=models.CharField(blank=True, default='', help_text='Person or community holding the rights to this tradition.', max_length=200),
        ),
    ]
