# Generated by Django 5.2.17 on 2026-10-03 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_consent_status_story_licence_story_origin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='consent_attested_at',
            field=models.DateTimeField(blank=True, help_text='When the consent decision was recorded.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='consent_attested_by',
            field=models.ForeignKey(blank=True, help_text='Who recorded the consent decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_attestations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='consent_basis',
            field=models.CharField(blank=True, default='', help_text='On what basis consent was granted or withheld.', max_length=200),
        ),
    ]
