# Generated by Django 5.2.17 on 2026-10-07 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_seeded_provenance_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted for review'), ('review_started', 'Review started'), ('approved', 'Approved and published'), ('rejected', 'Rejected'), ('changes_requested', 'Changes requested'), ('archived', 'Archived'), ('flags_resolved', 'Reports resolved'), ('consent_recorded', 'Consent decision recorded'), ('evidence_updated', 'Verification evidence updated'), ('source_verified', 'Source verified')], max_length=30)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ORAL_TRADITION', 'Oral tradition'), ('COMMUNITY_TESTIMONY', 'Community testimony'), ('BOOK', 'Book'), ('ACADEMIC_REFERENCE', 'Academic reference'), ('MUSEUM', 'Museum'), ('CULTURAL_INSTITUTION', 'Cultural institution'), ('ARCHIVE', 'Archive'), ('OFFICIAL_SOURCE', 'Official source'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('name', models.CharField(help_text='Title or description of the source (e.g. "Bamoun oral account, Foumban").', max_length=200)),
                ('author', models.CharField(blank=True, default='', help_text='Author, teller, or custodian of the source.', max_length=200)),
                ('institution', models.CharField(blank=True, default='', help_text='Publishing or holding institution, if any.', max_length=200)),
                ('url', models.URLField(blank=True, default='', help_text='Link to the source, when it is available online.')),
                ('reference', models.CharField(blank=True, default='', help_text='Citation detail: page, archive number, date of interview.', max_length=300)),
                ('notes', models.TextField(blank=True, default='', help_text='Why this source supports the story.')),
                ('is_verified', models.BooleanField(default=False, help_text='A reviewer checked this source against the story.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_verified', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_verified', models.BooleanField(default=False, help_text='A reliable/documented source was checked.')),
                ('community_validated', models.BooleanField(default=False, help_text='Members of the source community confirmed the account.')),
                ('expert_validated', models.BooleanField(default=False, help_text='A cultural expert or reviewer validated the content.')),
                ('references_confirmed', models.BooleanField(default=False, help_text='Historical/reference evidence was confirmed.')),
                ('consistency_confirmed', models.BooleanField(default=False, help_text='The account is internally consistent with related content.')),
                ('trust_score', models.PositiveIntegerField(default=0, help_text='Cached weighted evidence score (0-100). Recomputed on evidence change.')),
                ('notes', models.TextField(blank=True, default='', help_text='Reviewer notes on the verification evidence.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When a reviewer last confirmed the evidence.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='storyflag',
            name='resolution_action',
            field=models.CharField(blank=True, choices=[('corrected', 'Content corrected'), ('hidden', 'Content hidden'), ('dismissed', 'Report dismissed'), ('restored', 'Content restored')], default='', help_text='What was done about the report, once resolved.', max_length=20),
        ),
        migrations.AddField(
            model_name='storyflag',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who resolved the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_story_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('under_review', 'Under Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyflag',
            name='reason',
            field=models.CharField(choices=[('cultural_inaccuracy', 'Cultural Inaccuracy'), ('incorrect_information', 'Incorrect Information'), ('cultural_misrepresentation', 'Cultural Misrepresentation'), ('offensive_content', 'Offensive Content'), ('wrong_attribution', 'Wrong Attribution'), ('copyright_violation', 'Copyright Violation'), ('inappropriate_content', 'Inappropriate Content'), ('duplicate_content', 'Duplicate Content'), ('wrong_category', 'Wrong Category'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='storyflag',
            index=models.Index(fields=['resolved', '-created_at'], name='stories_sto_resolve_a44727_idx'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storysource',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storysource',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_story_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storyverification',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Reviewer who last updated the evidence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storyverification',
            name='story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='stories.story'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['story', '-created_at'], name='stories_mod_story_i_8557ee_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['action', '-created_at'], name='stories_mod_action_875df8_idx'),
        ),
        migrations.AddIndex(
            model_name='storysource',
            index=models.Index(fields=['story', '-created_at'], name='stories_sto_story_i_204d04_idx'),
        ),
        migrations.AddIndex(
            model_name='storysource',
            index=models.Index(fields=['source_type'], name='stories_sto_source__da2967_idx'),
        ),
    ]
