# Generated by Django 5.2.17 on 2026-10-06 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_codes', '0004_artifact_content_type_alter_artifact_category'),
        ('stories', '0005_story_seeded_provenance_note'),
        ('vr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GriotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', help_text='Language the answers should be written in.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='griot_conversations', to='qr_codes.artifact')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='griot_conversations', to='vr.vrexperience')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='griot_conversations', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='griot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GriotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Reader'), ('assistant', 'Griot')], max_length=12)),
                ('text', models.TextField()),
                ('provider', models.CharField(blank=True, default='', help_text='Answering engine: gemini, mock, or empty for reader messages.', max_length=40)),
                ('model_name', models.CharField(blank=True, default='', help_text='Model identifier that produced the answer.', max_length=80)),
                ('degraded', models.BooleanField(default=False, help_text='True when a development mock produced this, not a real model.')),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', help_text='Failure reason when no answer could be produced.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='griot_ai.griotconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='griotconversation',
            index=models.Index(fields=['user', '-updated_at'], name='griot_ai_gr_user_id_259c97_idx'),
        ),
        migrations.AddIndex(
            model_name='griotmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='griot_ai_gr_convers_747be7_idx'),
        ),
    ]
