# Generated by Django 5.2.4 on 2026-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF certificate file.', null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_url',
            field=models.URLField(blank=True, default='', help_text='Legacy URL to the generated PDF (kept for compatibility).'),
        ),
    ]
