# Generated by Django 5.2.4 on 2026-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_add_certificate_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Africa/Douala', help_text='IANA zone used to decide which calendar day activity counts on.', max_length=64),
        ),
    ]
