# Generated by Django 5.2.17 on 2026-10-03 12:29

from django.db import migrations, models


def repair_dedicated_reader(apps, schema_editor):
    """Give the one badge that shipped unearnable a requirement it can meet.

    ``Dedicated Reader`` was seeded with every requirement at 0 because the
    model had no field for what it actually asked for — a 3-day reading streak.
    The seed now supplies ``streak_required=3``, but a database seeded before
    this migration would keep the dead row, and ``get_or_create`` never updates
    an existing one. Scoped to ``streak_required=0`` so a badge an operator has
    since reconfigured is left alone.
    """
    Badge = apps.get_model('gamification', 'Badge')
    Badge.objects.filter(slug='dedicated-reader', streak_required=0).update(
        streak_required=3,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='streak_required',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive active days required to earn this badge.'),
        ),
        migrations.RunPython(repair_dedicated_reader, migrations.RunPython.noop),
    ]
