# Generated by Django 5.2.4 on 2026-08-07 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the artifact.')),
                ('category', models.CharField(choices=[('sculpture', 'Sculpture'), ('textile', 'Textile'), ('instrument', 'Musical Instrument'), ('jewelry', 'Jewelry'), ('pottery', 'Pottery'), ('mask', 'Mask'), ('weapon', 'Weapon'), ('fabric', 'Woven Fabric'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=20)),
                ('culture', models.CharField(blank=True, default='', help_text='Cultural group or kingdom (e.g., Bamoun, Bamileke).', max_length=200)),
                ('region', models.CharField(blank=True, default='', help_text='Geographic origin (e.g., Northwest Region).', max_length=100)),
                ('estimated_date', models.CharField(blank=True, default='', help_text='Estimated creation period (e.g., 19th century).', max_length=100)),
                ('materials', models.CharField(blank=True, default='', help_text='Materials used (e.g., bronze, wood, beads).', max_length=300)),
                ('dimensions', models.CharField(blank=True, default='', help_text='Physical dimensions.', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Primary artifact image.', null=True, upload_to='artifacts/images/')),
                ('image_blurhash', models.CharField(blank=True, default='', help_text='BlurHash placeholder for progressive image loading.', max_length=100)),
                ('additional_images', models.JSONField(blank=True, default=list, help_text='List of additional image URLs.')),
                ('qr_code_url', models.URLField(blank=True, default='', help_text='URL to the generated QR code image.')),
                ('qr_code_svg', models.TextField(blank=True, default='', help_text='SVG content of the QR code for inline display.')),
                ('deep_link_path', models.CharField(blank=True, default='', help_text='Deep link path (e.g., /artifact/my-artifact-slug).', max_length=200)),
                ('museum_name', models.CharField(blank=True, default='', help_text='Museum where this artifact is displayed.', max_length=200)),
                ('floor', models.CharField(blank=True, default='', help_text='Floor or level.', max_length=50)),
                ('display_case', models.CharField(blank=True, default='', help_text='Display case or exhibit number.', max_length=50)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this artifact is publicly visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_artifacts', to=settings.AUTH_USER_MODEL)),
                ('stories', models.ManyToManyField(blank=True, help_text='Stories related to this artifact.', related_name='artifacts', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, default='', help_text='Device type (iOS, Android, Web).', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_codes.artifact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['-created_at'], name='qr_codes_ar_created_95c5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['category'], name='qr_codes_ar_categor_70cfc3_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['culture'], name='qr_codes_ar_culture_1ef67a_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['is_published'], name='qr_codes_ar_is_publ_2d4b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['slug'], name='qr_codes_ar_slug_745fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['artifact', '-created_at'], name='qr_codes_qr_artifac_329f96_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['user', '-created_at'], name='qr_codes_qr_user_id_b6febe_idx'),
        ),
    ]
