# Generated by Django 5.2.17 on 2026-10-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0002_artifact_add_narrative_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.TextField(help_text='Short explanation of what the artifact looks like.'),
        ),
    ]
