# Generated by Django 5.2.17 on 2026-10-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0003_alter_artifact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='content_type',
            field=models.CharField(choices=[('kingdom', 'Kingdom'), ('landmark', 'Landmark'), ('artifact', 'Artifact'), ('legend', 'Legend'), ('culture', 'Culture'), ('unknown', 'Unclassified')], db_index=True, default='unknown', help_text='What kind of thing this is: kingdom, landmark, artifact, legend, culture.', max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='category',
            field=models.CharField(choices=[('sculpture', 'Sculpture'), ('textile', 'Textile'), ('instrument', 'Musical Instrument'), ('jewelry', 'Jewelry'), ('pottery', 'Pottery'), ('mask', 'Mask'), ('weapon', 'Weapon'), ('fabric', 'Woven Fabric'), ('tool', 'Tool'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
