# Generated by Django 5.2.17 on 2026-10-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_app', '0004_audionarrationjob_target_key_and_more'),
        ('qr_codes', '0004_artifact_content_type_alter_artifact_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VRExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Shown as the experience summary in Flutter and the loading screen.')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover image for the experience card.', null=True, upload_to='vr/thumbnails/')),
                ('scene_identifier', models.CharField(help_text='Unity scene name or addressable key (e.g. bamoun_gallery).', max_length=100, unique=True)),
                ('environment', models.CharField(blank=True, default='', help_text='Environment prefab identifier inside the Unity project.', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ful', 'Fula'), ('dua', 'Duala'), ('ewo', 'Ewondo'), ('bml', 'Bamileke'), ('other', 'Other')], default='en', help_text='Primary narration language of the experience.', max_length=10)),
                ('museum_name', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('culture', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Whether readers can be launched into this experience.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VR experience',
                'verbose_name_plural': 'VR experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VRExperienceArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order inside the scene.')),
                ('model_url', models.URLField(blank=True, default='', help_text='3D asset (glTF/GLB) URL or media path. Empty = placeholder mesh.')),
                ('model_scale', models.FloatField(default=1.0, help_text='Scale Unity applies to the loaded model.')),
                ('is_interactive', models.BooleanField(default=True, help_text='Whether the reader can select and inspect this artifact.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_placements', to='qr_codes.artifact')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='vr.vrexperience')),
                ('narration', models.ForeignKey(blank=True, help_text='Pre-generated narration replayed in VR. Reuses the TTS pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vr_placements', to='media_app.audionarrationjob')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vrexperience',
            name='artifacts',
            field=models.ManyToManyField(blank=True, help_text='Artifacts placed in this experience.', related_name='vr_experiences', through='vr.VRExperienceArtifact', to='qr_codes.artifact'),
        ),
        migrations.CreateModel(
            name='VRLaunchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the launch token. Never the token itself.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, help_text='Artifact the reader tapped, when they came from an artifact page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vr_launch_tokens', to='qr_codes.artifact')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_tokens', to='vr.vrexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_launch_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('completion_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=16)),
                ('progress', models.FloatField(default=0.0, help_text='Fraction of the experience completed, 0.0–1.0.')),
                ('xp_awarded', models.PositiveIntegerField(default=0, help_text='XP paid out for this session. Set once; guards against double awards.')),
                ('device_model', models.CharField(blank=True, default='', help_text='Headset/device the exchange came from, for support.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifacts_viewed', models.ManyToManyField(blank=True, help_text='Artifacts the reader actually opened. Validated against the experience.', related_name='vr_sessions', to='qr_codes.artifact')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vr.vrexperience')),
                ('launch_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vr.vrlaunchtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VR session',
                'verbose_name_plural': 'VR sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='vrexperienceartifact',
            constraint=models.UniqueConstraint(fields=('experience', 'artifact'), name='uniq_vr_placement'),
        ),
        migrations.AddIndex(
            model_name='vrexperience',
            index=models.Index(fields=['is_active'], name='vr_vrexperi_is_acti_dc6706_idx'),
        ),
        migrations.AddIndex(
            model_name='vrexperience',
            index=models.Index(fields=['slug'], name='vr_vrexperi_slug_bfdf58_idx'),
        ),
        migrations.AddIndex(
            model_name='vrlaunchtoken',
            index=models.Index(fields=['user', '-created_at'], name='vr_vrlaunch_user_id_91e0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='vrlaunchtoken',
            index=models.Index(fields=['expires_at', 'used_at'], name='vr_vrlaunch_expires_6093af_idx'),
        ),
        migrations.AddIndex(
            model_name='vrsession',
            index=models.Index(fields=['user', '-start_time'], name='vr_vrsessio_user_id_e8d2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='vrsession',
            index=models.Index(fields=['experience', '-start_time'], name='vr_vrsessio_experie_c936f4_idx'),
        ),
        migrations.AddIndex(
            model_name='vrsession',
            index=models.Index(fields=['completion_status'], name='vr_vrsessio_complet_f4780e_idx'),
        ),
    ]
