# Generated by Django 5.2.17 on 2026-10-04 01:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_codes', '0004_artifact_content_type_alter_artifact_category'),
        ('stories', '0005_story_seeded_provenance_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(max_length=500)),
                ('source_type', models.CharField(choices=[('museum', 'Museum'), ('government', 'Government / ministry'), ('unesco', 'UNESCO'), ('research', 'Academic or research'), ('archive', 'Digital archive'), ('other', 'Other')], default='other', max_length=20)),
                ('reliability', models.CharField(choices=[('authoritative', 'Authoritative / official'), ('scholarly', 'Scholarly / peer-reviewed'), ('curated', 'Curated secondary source'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('is_builtin', models.BooleanField(default=False, help_text='Seeded from source_config; still editable by an administrator.')),
                ('max_pages', models.PositiveIntegerField(default=25)),
                ('max_depth', models.PositiveSmallIntegerField(default=1, help_text='0 = only the seed URLs, 1 = their links, and so on.')),
                ('request_delay', models.FloatField(default=2.0, help_text='Seconds between requests to this source.')),
                ('timeout', models.PositiveIntegerField(default=20)),
                ('max_response_bytes', models.PositiveIntegerField(default=5000000)),
                ('relevance_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Hostnames the fetcher may contact for this source. Empty means base_url only.')),
                ('seed_urls', models.JSONField(blank=True, default=list, help_text='Pages to start from. Empty means base_url alone. A list, not a single URL, because a museum site usually has a collection index and an institution page worth reading separately.')),
                ('include_url_patterns', models.JSONField(blank=True, default=list)),
                ('exclude_url_patterns', models.JSONField(blank=True, default=list)),
                ('default_licence', models.CharField(choices=[('all_rights_reserved', 'All rights reserved'), ('cc_by', 'CC BY 4.0'), ('cc_by_sa', 'CC BY-SA 4.0'), ('cc_by_nc', 'CC BY-NC 4.0'), ('cc_by_nc_sa', 'CC BY-NC-SA 4.0'), ('public_domain', 'Public domain'), ('undetermined', 'Undetermined')], default='undetermined', help_text='Applied to imported items unless the page states otherwise. Defaults to undetermined: §6 says do not assume reuse is permitted.', max_length=40)),
                ('allow_media_download', models.BooleanField(default=False, help_text='Leave off unless the source explicitly licenses reuse. When off, media is recorded by URL and attribution only.')),
                ('contact_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'crawl sources',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('pages_skipped', models.PositiveIntegerField(default=0)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_imported', models.PositiveIntegerField(default=0)),
                ('duplicates_found', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null for a scheduled or CLI run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='heritage_crawl.crawlsource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1000)),
                ('url_hash', models.CharField(db_index=True, help_text='SHA-256 of the normalised URL; the cheap duplicate key.', max_length=64)),
                ('extracted_title', models.CharField(blank=True, default='', max_length=500)),
                ('extracted_alt_title', models.CharField(blank=True, default='', max_length=500)),
                ('extracted_description', models.TextField(blank=True, default='')),
                ('extracted_content', models.TextField(blank=True, default='', help_text='Plain text. Raw HTML is never stored.')),
                ('extracted_metadata', models.JSONField(blank=True, default=dict)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('relevance_reasons', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('discovered', 'Discovered'), ('fetched', 'Fetched'), ('extracted', 'Extracted'), ('normalized', 'Normalized'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped — not relevant / disallowed'), ('error', 'Error'), ('imported', 'Imported for review')], default='discovered', max_length=20)),
                ('error_type', models.CharField(blank=True, default='', max_length=60)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_items', to='qr_codes.artifact')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_items', to='stories.story')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='heritage_crawl.crawljob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='heritage_crawl.crawlsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1000)),
                ('author', models.CharField(blank=True, default='', max_length=300)),
                ('institution', models.CharField(blank=True, default='', max_length=300)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extraction_method', models.CharField(choices=[('full_text', 'Full text extracted'), ('metadata_only', 'Metadata and summary only'), ('manual_entry', 'Entered by hand')], default='metadata_only', max_length=20)),
                ('licence', models.CharField(blank=True, default='', max_length=40)),
                ('attribution', models.CharField(blank=True, default='', max_length=500)),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('extracted_verbatim', models.BooleanField(default=False, help_text='True when the stored text is the source wording, unmodified. False means it was summarised or normalised by the system.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, help_text='Null when a reference was added to a Story/Artifact directly.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='heritage_crawl.crawleditem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='heritage_crawl.crawlsource')),
            ],
            options={
                'ordering': ['-crawled_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=12)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('original_url', models.URLField(max_length=1000)),
                ('local_path', models.CharField(blank=True, default='', help_text='Relative to MEDIA_ROOT. Empty when the file was not downloaded.', max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('licence', models.CharField(blank=True, default='', max_length=40)),
                ('attribution', models.CharField(blank=True, default='', max_length=500)),
                ('alt_text', models.CharField(blank=True, default='', max_length=300)),
                ('reused', models.BooleanField(default=False, help_text='Whether reuse permission was established.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_media', to='qr_codes.artifact')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='heritage_crawl.crawleditem')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_media', to='stories.story')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['checksum'], name='heritage_cr_checksu_6004fa_idx'), models.Index(fields=['original_url'], name='heritage_cr_origina_1fd89b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crawleditem',
            index=models.Index(fields=['job', 'processing_status'], name='heritage_cr_job_id_1f6378_idx'),
        ),
        migrations.AddIndex(
            model_name='crawleditem',
            index=models.Index(fields=['url_hash'], name='heritage_cr_url_has_794a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='crawleditem',
            index=models.Index(fields=['processing_status', '-created_at'], name='heritage_cr_process_08d850_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcereference',
            index=models.Index(fields=['original_url'], name='heritage_cr_origina_8aceae_idx'),
        ),
    ]
