# Generated by Django 5.2.17 on 2026-10-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleditem',
            name='processing_status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('fetched', 'Fetched'), ('extracted', 'Extracted'), ('normalized', 'Normalized'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped — not relevant / disallowed'), ('error', 'Error'), ('imported', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_correction', 'Needs correction')], default='discovered', max_length=20),
        ),
    ]
